### ISSUE TITLE
I-frame checksum

### ISSUE THREAD

**Issue by kabir-plod** [CG3002-group02/dance#2]
`int checksum = crc16(&iframe[2], (sizeof(iframe) / sizeof(iframe[0])) - 2);`
- Should start from &iframe[1] (2nd byte)
- I think sizeof returns total memory allocated to array, not amount written. Check how many bytes you write instead

**Comment by Infinity-Ace** [comment]
Resolved! Start, Stop & check bytes were converted to characters instead of bytes. Used len function to check length of string
